/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GestionContrasenas_GUI;

import GestionContrasenas_DTO.Registro;

/**
 * PantallaRegistro (JDialog). Ventana modal que contiene el formulario para el
 * alta de una nueva contraseña
 *
 * @author Jaime
 */
public class PantallaRegistro extends javax.swing.JDialog {

    /**
     * Constructor del JDialog.
     *
     * @param parent La ventana principal (PantallaPrincipal) que invoca este
     * diálogo.
     * @param modal Indica si la ventana es modal (true), bloqueando la ventana
     * padre.
     */
    public PantallaRegistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // Configuración de la ventana (Tamaño, centrado y estilo)
        setTitle("NotePass - Nuevo Registro"); // Título personalizado
        setSize(800, 550);                     // Mismo tamaño que la Principal (600x500)
        setLocationRelativeTo(null);           // Centrada en el monitor
        setResizable(false);                   // (Opcional) Impide que le cambien el tamaño para no romper el diseño
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlFondoRegistro = new javax.swing.JPanel();
        lblTituloRegistro = new javax.swing.JLabel();
        lblServicio = new javax.swing.JLabel();
        txtServicio = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        lblusuario = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        pwdFContrasena = new javax.swing.JPasswordField();
        chkMostrar = new javax.swing.JCheckBox();
        btnGenerar = new javax.swing.JButton();
        lblCategoria = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        lblSeguridad = new javax.swing.JLabel();
        rbtnBaja = new javax.swing.JRadioButton();
        rbtnAlta = new javax.swing.JRadioButton();
        chkDobleFactor = new javax.swing.JCheckBox();
        btnRegistrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblNotas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaNotas = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlFondoRegistro.setBackground(new java.awt.Color(45, 48, 56));

        lblTituloRegistro.setBackground(new java.awt.Color(240, 240, 240));
        lblTituloRegistro.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        lblTituloRegistro.setForeground(new java.awt.Color(240, 240, 240));
        lblTituloRegistro.setText("REGISTRO CONTRASEÑA");

        lblServicio.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        lblServicio.setForeground(new java.awt.Color(240, 240, 240));
        lblServicio.setText("Servicio");

        txtServicio.setBackground(new java.awt.Color(40, 43, 50));
        txtServicio.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        txtServicio.setForeground(new java.awt.Color(240, 240, 240));

        txtUsuario.setBackground(new java.awt.Color(40, 43, 50));
        txtUsuario.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(240, 240, 240));

        lblusuario.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        lblusuario.setForeground(new java.awt.Color(240, 240, 240));
        lblusuario.setText("Usuario");

        lblContrasena.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(240, 240, 240));
        lblContrasena.setText("Contraseña");

        pwdFContrasena.setBackground(new java.awt.Color(40, 43, 50));
        pwdFContrasena.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        pwdFContrasena.setForeground(new java.awt.Color(240, 240, 240));
        pwdFContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdFContrasenaActionPerformed(evt);
            }
        });

        chkMostrar.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        chkMostrar.setForeground(new java.awt.Color(240, 240, 240));
        chkMostrar.setText("Mostrar");
        chkMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMostrarActionPerformed(evt);
            }
        });

        btnGenerar.setBackground(new java.awt.Color(180, 180, 180));
        btnGenerar.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        btnGenerar.setForeground(new java.awt.Color(0, 0, 0));
        btnGenerar.setText("GENERAR");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        lblCategoria.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(240, 240, 240));
        lblCategoria.setText("Categoria");

        cmbCategoria.setBackground(new java.awt.Color(180, 180, 180));
        cmbCategoria.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        cmbCategoria.setForeground(new java.awt.Color(0, 0, 0));
        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red Social", "Correo", "Trabajo", "Personal" }));

        lblSeguridad.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        lblSeguridad.setForeground(new java.awt.Color(240, 240, 240));
        lblSeguridad.setText("Seguridad");

        buttonGroup1.add(rbtnBaja);
        rbtnBaja.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        rbtnBaja.setForeground(new java.awt.Color(240, 240, 240));
        rbtnBaja.setText("Baja");

        buttonGroup1.add(rbtnAlta);
        rbtnAlta.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        rbtnAlta.setForeground(new java.awt.Color(240, 240, 240));
        rbtnAlta.setText("Alta");

        chkDobleFactor.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        chkDobleFactor.setForeground(new java.awt.Color(240, 240, 240));
        chkDobleFactor.setText("¿Activar 2FA?");

        btnRegistrar.setBackground(new java.awt.Color(180, 180, 180));
        btnRegistrar.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(80, 120, 140));
        btnVolver.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(240, 240, 240));
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lblNotas.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        lblNotas.setForeground(new java.awt.Color(240, 240, 240));
        lblNotas.setText("Notas");

        txtAreaNotas.setBackground(new java.awt.Color(40, 43, 50));
        txtAreaNotas.setColumns(20);
        txtAreaNotas.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        txtAreaNotas.setForeground(new java.awt.Color(240, 240, 240));
        txtAreaNotas.setRows(5);
        jScrollPane1.setViewportView(txtAreaNotas);

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Doble factor");

        javax.swing.GroupLayout pnlFondoRegistroLayout = new javax.swing.GroupLayout(pnlFondoRegistro);
        pnlFondoRegistro.setLayout(pnlFondoRegistroLayout);
        pnlFondoRegistroLayout.setHorizontalGroup(
            pnlFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoRegistroLayout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addGroup(pnlFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoRegistroLayout.createSequentialGroup()
                        .addGroup(pnlFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblServicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblusuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblContrasena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFondoRegistroLayout.createSequentialGroup()
                                .addComponent(pwdFContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlFondoRegistroLayout.createSequentialGroup()
                                .addGroup(pnlFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(txtServicio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(pnlFondoRegistroLayout.createSequentialGroup()
                                .addGroup(pnlFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlFondoRegistroLayout.createSequentialGroup()
                        .addGroup(pnlFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFondoRegistroLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(lblTituloRegistro))
                            .addGroup(pnlFondoRegistroLayout.createSequentialGroup()
                                .addGroup(pnlFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblSeguridad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(pnlFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoRegistroLayout.createSequentialGroup()
                                            .addComponent(rbtnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(rbtnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(chkDobleFactor, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(pnlFondoRegistroLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(199, Short.MAX_VALUE))))
        );
        pnlFondoRegistroLayout.setVerticalGroup(
            pnlFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoRegistroLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTituloRegistro)
                .addGap(18, 18, 18)
                .addGroup(pnlFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServicio)
                    .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnlFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasena)
                    .addComponent(pwdFContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeguridad)
                    .addComponent(rbtnBaja)
                    .addComponent(rbtnAlta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDobleFactor)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNotas))
                .addGap(54, 54, 54)
                .addGroup(pnlFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnVolver))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondoRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondoRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Manejador del evento click en el JPasswordField (no funcional, se
     * mantiene por estructura).
     */
    private void pwdFContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdFContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdFContrasenaActionPerformed
    
    /**
     * Manejador del evento click en el CheckBox MOSTRAR. Alterna la visibilidad
     * de la contraseña en el JPasswordField (setEchoChar).
     */
    private void chkMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMostrarActionPerformed
        if (chkMostrar.isSelected()) {
            // Muestra el texto (carácter de eco nulo)
            pwdFContrasena.setEchoChar((char) 0);
        } else {
            // Oculta el texto (carácter de eco *)
            pwdFContrasena.setEchoChar('*');
        }
    }//GEN-LAST:event_chkMostrarActionPerformed

    /**
     * Manejador del evento click en el botón GENERAR. Genera una contraseña
     * aleatoria y compleja de 12 caracteres.
     */
    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        String mayusculas = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String minusculas = "abcdefghijklmnopqrstuvwxyz";
        String numeros = "0123456789";
        String simbolos = "!@#$%^&*()_+-=[]?";

        String conjunto = mayusculas + minusculas + numeros + simbolos;

        String contrasenaGenerada = "";
        // Bucle para generar 12 caracteres aleatorios
        for (int i = 0; i < 12; i++) {
            int aleatorio = (int) (Math.random() * conjunto.length());
            contrasenaGenerada += conjunto.charAt(aleatorio);
        }
        // Muestra la contraseña generada en el campo JPasswordField
        pwdFContrasena.setText(contrasenaGenerada);
    }//GEN-LAST:event_btnGenerarActionPerformed

    /**
     * Manejador del evento click en el botón VOLVER (JOptionPane de
     * Confirmación). Pregunta al usuario si desea salir, advirtiendo sobre la
     * pérdida de datos.
     */
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        //Lanzamos la pregunta de confirmación
        int opcion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Volver a la pantalla principal?\nSe perderán los datos que no hayas guardado.",
                "Cerrar Ventana",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE); // Icono de advertencia

        //Verificamos la respuesta
        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            // Solo cerramos si el usuario dice "SÍ"
            this.dispose();
        }

    }//GEN-LAST:event_btnVolverActionPerformed
    
    /**
     * Manejador del evento click en el botón REGISTRAR. Implementa el flujo
     * completo: Validación, Confirmación, Creación del DTO y envío a la
     * PantallaPrincipal.
     */
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        //1. Captura y validación
        String servicio = txtServicio.getText();
        String usuario = txtUsuario.getText();
        String contrasena = new String(pwdFContrasena.getPassword());

        if (servicio.isEmpty() || contrasena.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El servicio y la contraseña son obligatorios");
            return;
        }
        
        //2. Captura de datos especiales
        String categoria = cmbCategoria.getSelectedItem().toString();
        boolean dobleFactor = chkDobleFactor.isSelected();
        String notas = txtAreaNotas.getText();
        
        //Determinamos el valor del Radiobutton
        String seguridad;
        if (rbtnAlta.isSelected() == true) {
            seguridad = "Alta";
        } else {
            seguridad = "Baja";
        }
        
        //3. Confirmación y envio
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, "¿Registrar nueva contraseña?", "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {

            //Creamos el objeto DTO (El paquete con todos los datos)
            Registro nuevoRegistro = new GestionContrasenas_DTO.Registro(servicio, usuario, contrasena, categoria, seguridad, dobleFactor, notas);

            //Mostramos el resumen usando .toString();
            javax.swing.JOptionPane.showMessageDialog(this, nuevoRegistro.toString());

            // Enviamos a la pantalla principal usando .getParent()
            // Recuperamos a la ventana "madre" (this.getParent) y la convertimos a PantallaPrincipal
            PantallaPrincipal padre = (GestionContrasenas_GUI.PantallaPrincipal) this.getParent();
            padre.anadirRegistro(nuevoRegistro);

            // Cierra esta ventana
            this.dispose();
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkDobleFactor;
    private javax.swing.JCheckBox chkMostrar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblNotas;
    private javax.swing.JLabel lblSeguridad;
    private javax.swing.JLabel lblServicio;
    private javax.swing.JLabel lblTituloRegistro;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JPanel pnlFondoRegistro;
    private javax.swing.JPasswordField pwdFContrasena;
    private javax.swing.JRadioButton rbtnAlta;
    private javax.swing.JRadioButton rbtnBaja;
    private javax.swing.JTextArea txtAreaNotas;
    private javax.swing.JTextField txtServicio;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
