package GestionContrasenas_GUI;

import GestionContrasenas_DTO.Registro;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;

/**
 *
 * @author Jaime
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName());

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        
        setTitle("NotePass - Gestor v1.0"); //titulo de la ventana
        setSize(800, 550); //Tamaño de nuestra App
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //Al pulsar sobre la X se cierra el programa.
        setLocationRelativeTo(null); //La pantalla principal aparece en el centro del monitor.
        inicializarTabla();
    }

    //Metodo inicializar tabla
    private void inicializarTabla() {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Servicio", "Usuario", "Contraseña", "Categoria", "Seguridad", "Doble Factor", "Notas"});
        tblContrasenas.setModel(dtm);
    }
    
    
    
    public void anadirRegistro(Registro registro) {
        DefaultTableModel dtm = (DefaultTableModel) tblContrasenas.getModel();
        dtm.addRow(registro.toArrayStringRegistro());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPaneContasenas = new javax.swing.JScrollPane();
        tblContrasenas = new javax.swing.JTable();
        pnlBotones = new javax.swing.JPanel();
        btnNuevaContrasena = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(45, 48, 56));

        pnlFondo.setBackground(new java.awt.Color(45, 48, 56));
        pnlFondo.setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(240, 240, 240));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("NOTEPASS - V1.0");
        pnlFondo.add(lblTitulo, java.awt.BorderLayout.PAGE_START);

        jScrollPaneContasenas.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 50, 20, 50));
        jScrollPaneContasenas.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jScrollPaneContasenas.setMaximumSize(new java.awt.Dimension(500, 300));

        tblContrasenas.setBackground(new java.awt.Color(240, 240, 240));
        tblContrasenas.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        tblContrasenas.setForeground(new java.awt.Color(40, 43, 50));
        tblContrasenas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Servicio", "Usuario", "Contraseña", "Categoria", "Seguridad", "2FA", "Notas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblContrasenas.setGridColor(new java.awt.Color(120, 150, 160));
        tblContrasenas.setMaximumSize(new java.awt.Dimension(400, 140));
        tblContrasenas.setShowGrid(true);
        jScrollPaneContasenas.setViewportView(tblContrasenas);

        pnlFondo.add(jScrollPaneContasenas, java.awt.BorderLayout.CENTER);

        pnlBotones.setBackground(new java.awt.Color(45, 48, 56));

        btnNuevaContrasena.setBackground(new java.awt.Color(180, 180, 180));
        btnNuevaContrasena.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        btnNuevaContrasena.setForeground(new java.awt.Color(0, 0, 0));
        btnNuevaContrasena.setText("REGISTRAR CONTRASEÑA");
        btnNuevaContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaContrasenaActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(80, 120, 140));
        btnSalir.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(240, 240, 240));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap(448, Short.MAX_VALUE)
                .addComponent(btnNuevaContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnNuevaContrasena))
                .addGap(0, 43, Short.MAX_VALUE))
        );

        pnlFondo.add(pnlBotones, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaContrasenaActionPerformed
        PantallaRegistro pantallaRegistro = new PantallaRegistro(this, true);
        
        pantallaRegistro.setVisible(true);
    }//GEN-LAST:event_btnNuevaContrasenaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevaContrasena;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPaneContasenas;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JTable tblContrasenas;
    // End of variables declaration//GEN-END:variables
}
